"""
SPDX-License-Identifier: Apache-2.0
"""

import vastorbit._config.config as conf
from vastorbit._utils._logo import vastorbit_logo_html, vastorbit_logo_str

if conf.get_import_success("IPython"):
    from IPython.display import display, Markdown


def help_start() -> None:
    """
    vastorbit Interactive Help (FAQ).
    """
    img1 = vastorbit_logo_html(size="10%")
    img2 = vastorbit_logo_str()
    if conf.get_import_success("IPython"):
        message = img1
    else:
        message = img2
    message += (
        "\n\n&#128226; Welcome to the <b>vastorbit</b> help module."
        "\n\nThis module can help you connect to VAST, "
        "create a VastFrame, load your data, and more.\n "
        "- <b>[Enter  0]</b> Overview of the library\n "
        "- <b>[Enter  1]</b> Load an example dataset\n "
        "- <b>[Enter  2]</b> View an example of data analysis with vastorbit\n "
        "- <b>[Enter  3]</b> Contribute on GitHub\n "
        "- <b>[Enter  4]</b> View the SQL code generated by a VastFrame and "
        "the time elapsed for the query\n "
        "- <b>[Enter  5]</b> Load your own dataset into VAST \n "
        "- <b>[Enter  6]</b> Write SQL queries in Jupyter\n "
        "- <b>[Enter -1]</b> Exit"
    )
    if not conf.get_import_success("IPython"):
        message = message.replace("<b>", "").replace("</b>", "")
    if conf.get_import_success("IPython"):
        display(Markdown(message))
    else:
        print(message)
    try:
        response = int(input())
    except TypeError:
        print("Invalid choice.\nPlease enter a number between 0 and 11.")
        try:
            response = int(input())
        except TypeError:
            print("Invalid choice.\nRerun the help_start function when you need help.")
            return
    link = None
    if response == 0:
        link = (
            "https://www.VAST.com/python/documentation/0.1.x/html/getting_started.html"
        )
    elif response == 1:
        link = "https://www.VAST.com/python/documentation/0.1.x/html/datasets.html"
    elif response == 2:
        link = "https://www.VAST.com/python/documentation/0.1.x/html/examples.html"
    elif response == 3:
        link = "https://github.com/vast-data/VAST-Orbit/"
    elif response == 4:
        link = "https://www.VAST.com/python/documentation/0.1.x/html/api/vastorbit.set_option.html"
    elif response == 5:
        link = "https://www.VAST.com/python/documentation/0.1.x/html/datasets.html"
    elif response == 6:
        link = "https://www.VAST.com/python/documentation/0.1.x/html/api/vastorbit.jupyter.extensions.sql_magic.sql_magic.html"
    elif response == -1:
        message = "Thank you for using the vastorbit help module."
    elif response == 666:
        message = (
            "Thank you so much for using this library. My only purpose is to solve "
            "real Big Data problems in the context of Data Science. I worked years "
            "to be able to create this API and give you a real way to analyze your "
            "data.\n\nYour devoted Data Scientist: <i>Badr Ouali</i>"
        )
    else:
        message = "Invalid choice.\nPlease enter a number between -1 and 6."
    if 0 <= response <= 6:
        if not conf.get_import_success("IPython"):
            message = f"Please go to {link}"
        else:
            message = f"Please go to <a href='{link}'>{link}</a>"
    if conf.get_import_success("IPython"):
        display(Markdown(message))
    else:
        print(message)
