blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/vastdata-dev/vastorbit/tree/master/docs
    about: Check the documentation for guides and API reference.
  - name: Slack Community
    url: https://vastsupport.slack.com
    about: Join our Slack channel for questions and community support.