"""
SPDX-License-Identifier: Apache-2.0
"""

from vastorbit.sql.functions.analytic import (
    avg,
    bool_and,
    bool_or,
    bool_xor,
    conditional_change_event,
    conditional_true_event,
    count,
    lag,
    lead,
    max,
    median,
    min,
    nth_value,
    quantile,
    rank,
    row_number,
    std,
    sum,
    var,
)
from vastorbit.sql.functions.conditional import case_when, decode
from vastorbit.sql.functions.date import (
    date,
    day,
    dayofweek,
    dayofyear,
    extract,
    getdate,
    getutcdate,
    hour,
    interval,
    minute,
    microsecond,
    month,
    overlaps,
    quarter,
    round_date,
    second,
    timestamp,
    week,
    year,
)
from vastorbit.sql.functions.math import E, INF, NAN, PI, TAU
from vastorbit.sql.functions.math import (
    apply,
    abs,
    acos,
    asin,
    atan,
    atan2,
    cbrt,
    ceil,
    comb,
    cos,
    cosh,
    cot,
    degrees,
    distance,
    exp,
    factorial,
    floor,
    gamma,
    hash,
    isfinite,
    isinf,
    isnan,
    lgamma,
    ln,
    log,
    radians,
    round,
    sign,
    sin,
    sinh,
    sqrt,
    tan,
    tanh,
    trunc,
)
from vastorbit.sql.functions.null_handling import coalesce, nullifzero, zeroifnull
from vastorbit.sql.functions.random import random, randomint, seeded_random
from vastorbit.sql.functions.regexp import (
    regexp_count,
    regexp_ilike,
    regexp_instr,
    regexp_like,
    regexp_replace,
    regexp_substr,
)
from vastorbit.sql.functions.string import (
    length,
    lower,
    substr,
    upper,
    edit_distance,
    soundex,
    soundex_matches,
    jaro_distance,
    jaro_winkler_distance,
)
