name: Pylint
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -e .
          pip install -r requirements-dev.txt
          pip install -r requirements-testing.txt

      - name: Analyze code with pylint
        run: |
          pylint --fail-under=9.0 \
            --init-hook='import sys; sys.setrecursionlimit(10000)' \
            --disable=typecheck,C,R,W0212 \
            vastorbit/